---
deployment:
  tasks:
    - export LOGPATHFILE=~/public_html/deployment.log
    - export DEPLOYPATH=~/public_html/mail/ >> $LOGPATHFILE 2>&1
    - /bin/rm -R $DEPLOYPATH >> $LOGPATHFILE 2>&1
    - /bin/cp -a ./. $DEPLOYPATH >> $LOGPATHFILE 2>&1
    - ls /bin/ -l >> $LOGPATHFILE 2>&1